apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-2
  name: jvb-udp-2
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - name: "8080"
    port: 8080
    protocol: UDP
    targetPort: 8080
    nodePort: 30301
  - name: "10000"
    port: 10000
    targetPort: 10000
  selector:
    k8s-app: jvb